# Generated by Django 5.0.7 on 2024-07-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to='')),
                ('kills', models.IntegerField(default=0, verbose_name='Bajas')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
